g & d controller DoingLogs
[because below error was called on localhost]
NoMethodError in DoingLogsController#index
undefined method `all' for DoingLog:Module